#Postgres Configuration
spring.datasource.url=jdbc:postgresql://dpg-d7jrmqlckfvc73e0n5h0-a.singapore-postgres.render.com/moneymanager_q4k1
spring.datasource.username=moneymanager_q4k1_user
spring.datasource.password=S9XTd7yspdQRl4wm9q1IeX51PW4Gb7Fq